### ISSUE TITLE
Telly puts a space in the token of the Vaders link when FFMpeg enabled

### ISSUE THREAD

**Issue by cmcpherson274** [tellytv/telly#181]
**telly release with the issue:**
telly, version 1.1.0.2 (branch: dev, revision: f1de7f04430f9f6d35ad7caf55d4d5360a1d681c)
  build user:       root@231f8db4ee44
  build date:       20180822-04:18:21
  go version:       go1.10.3

**Last working telly release (if known):** N/A

**Operating environment (Docker/Windows/Linux/QNAP, etc.):** Windows Server 2016

**Description of problem:**
When FFMpeg is enabled sometimes Telly puts a space in the token of the vaders link. This prevents the stream from playing.

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
```toml
# THIS SECTION IS REQUIRED ########################################################################
[Discovery]                                    # most likely you won't need to change anything here
  Device-Auth = "telly123"                     # These settings are all related to how telly identifies
  Device-ID = 12345678                         # itself to Plex.
  Device-UUID = ""
  Device-Firmware-Name = "hdhomeruntc_atsc"
  Device-Firmware-Version = "20150826"
  Device-Friendly-Name = "telly"
  Device-Manufacturer = "Silicondust"
  Device-Model-Number = "HDTC-2US"
  SSDP = true

# THIS SECTION IS REQUIRED ########################################################################
[IPTV]
  Streams = 5               # number of simultaneous streams that the telly virtual DVR will provide
                            # This is often 1, but is set by your iptv provider; for example, 
                            # Vaders provides 5
  Starting-Channel = 10000  # When telly assigns channel numbers it will start here
  XMLTV-Channels = true     # if true, any channel numbers specified in your M3U file will be used.
  FFMpeg = true             # if this is uncommented, streams are buffered through ffmpeg; 
                            # ffmpeg must be installed and on your $PATH
                            # if you want to use this with Docker, be sure you use the correct docker image
# if you DO NOT WANT TO USE FFMPEG leave this commented; DO NOT SET IT TO FALSE
  
# THIS SECTION IS REQUIRED ########################################################################
[Log]
  Level = "info"            # Only log messages at or above the given level. [debug, info, warn, error, fatal]
  Requests = true           # Log HTTP requests made to telly

# THIS SECTION IS REQUIRED ########################################################################
[Web]
  Base-Address = "IP_ADDRESS:2001"   # Set this to the IP address of the machine telly runs on
  Listen-Address = "IP_ADDRESS:2001" # this can stay as-is

# THIS SECTION IS OPTIONAL ========================================================================
#[SchedulesDirect]           # If you have a Schedules Direct account, fill in details and then
                             # UNCOMMENT THIS SECTION
#  Username = ""             # This is under construction; Vader is the only provider
#  Password = ""             # that works with it fully at this time

# AT LEAST ONE SOURCE IS REQUIRED #################################################################
# DELETE OR COMMENT OUT SOURCES THAT YOU ARE NOT USING ############################################
# NONE OF THESE EXAMPLES WORK AS-IS; IF YOU DON'T CHANGE IT, DELETE IT ############################
[[Source]]
  Provider = "Custom"
  M3U = "VGET.m3u"  # These can be either URLs or fully-qualified paths.
  # EPG = "http://myprovider.com/epg.xml"
  # THE FOLLOWING KEYS ARE OPTIONAL IN THEORY, REQUIRED IN PRACTICE
  Filter = "Sports|Premium Movies|United States.*|USA"
  FilterKey = "group-title" # FilterKey normally defaults to whatever the provider file says is best, 
                            # otherwise you must set this.
  FilterRaw = false         # FilterRaw will run your regex on the entire line instead of just specific keys.
  Sort = "group-title"      # Sort will alphabetically sort your channels by the M3U key provided
# END TELLY CONFIG  ###############################################################################
```

**Command line used to run telly [if applicable]:**
```
telly
```

**telly or docker log:**
```
[36mINFO[0m[2018-08-30T12:48:10-04:00] [http @ 0000016ac777b000] HTTP error 403 Forbidden                                   
[36mINFO[0m[2018-08-30T12:48:10-04:00] http://vapi.vaders.tv/play/####.ts?token=TOKEN_PART_BEFORE_SPACE TOKEN_PART_AFTER_SPACE=: Server returned 403 Forbidden (access denied)
[36mINFO[0m[2018-08-30T12:48:10-04:00] Stopped streaming 10122
```
