### ISSUE TITLE
telly 1.5 @ macOS does not work

### ISSUE THREAD

**Issue by niXta1** [tellytv/telly#193]
**telly release with the issue:**
telly, version 1.5.0 (branch: HEAD, revision: 811ea6be581f9bc8f2956d7c3892f2754b948e4d)
  build user:       root@8534dbdccf84
  build date:       20180907-03:23:00
  go version:       go1.10.3

**Last working telly release (if known):**
1.03

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**
MacOS

**Description of problem:**
telly starts but does not load channels and can't be connected to from Plex.

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml
# THIS SECTION IS REQUIRED ########################################################################
[Discovery]                                    # most likely you won't need to change anything here
  Device-Auth = "telly123"                     # These settings are all related to how telly identifies
  Device-ID = 12345678                         # itself to Plex.
  Device-UUID = ""
  Device-Firmware-Name = "hdhomeruntc_atsc"
  Device-Firmware-Version = "20150826"
  Device-Friendly-Name = "telly"
  Device-Manufacturer = "Silicondust"
  Device-Model-Number = "HDTC-2US"
  SSDP = true

# THIS SECTION IS REQUIRED ########################################################################
[IPTV]
  Streams = 1               # number of simultaneous streams that the telly virtual DVR will provide
                            # This is often 1, but is set by your iptv provider; for example,
                            # Vaders provides 5
  Starting-Channel = 10000  # When telly assigns channel numbers it will start here
  XMLTV-Channels = true     # if true, any channel numbers specified in your M3U file will be used.
# FFMpeg = true             # if this is uncommented, streams are buffered through ffmpeg;
                            # ffmpeg must be installed and on your $PATH
                            # if you want to use this with Docker, be sure you use the correct docker image
# if you DO NOT WANT TO USE FFMPEG leave this commented; DO NOT SET IT TO FALSE

# THIS SECTION IS REQUIRED ########################################################################
[Log]
  Level = "debug"            # Only log messages at or above the given level. [debug, info, warn, error, fatal]
  Requests = true           # Log HTTP requests made to telly

# THIS SECTION IS REQUIRED ########################################################################
[Web]
  Base-Address = "192.168.1.35:6077"   # Set this to the IP address of the machine telly runs on
  Listen-Address = "0.0.0.0:6077" # this can stay as-is

# THIS SECTION IS OPTIONAL ========================================================================
#[SchedulesDirect]           # If you have a Schedules Direct account, fill in details and then
                             # UNCOMMENT THIS SECTION
#  Username = ""             # This is under construction; Vader is the only provider
#  Password = ""             # that works with it fully at this time

# AT LEAST ONE SOURCE IS REQUIRED #################################################################
# DELETE OR COMMENT OUT SOURCES THAT YOU ARE NOT USING ############################################
# NONE OF THESE EXAMPLES WORK AS-IS; IF YOU DON'T CHANGE IT, DELETE IT ############################
#[[Source]]
#  Name = ""                 # Name is optional and is used mostly for logging purposes
#  Provider = "Vaders"       # named providers currently supported are "Vaders", "area51", "Iris"
# IF YOUR PROVIDER IS NOT ONE OF THE ABOVE, CONFIGURE IT AS A "Custom" PROVIDER; SEE BELOW
#  Username = "YOUR_IPTV_USERNAME"
#  Password = "YOUR_IPTV_PASSWORD"
  # THE FOLLOWING KEYS ARE OPTIONAL IN THEORY, REQUIRED IN PRACTICE
#  Filter = "Sports|Premium Movies|United States.*|USA"
#  FilterKey = "group-title" # FilterKey normally defaults to whatever the provider file says is best,
#                            # otherwise you must set this.
#  FilterRaw = false         # FilterRaw will run your regex on the entire line instead of just specific keys.
#  Sort = "group-title"      # Sort will alphabetically sort your channels by the M3U key provided

#[[Source]]
#  Name = ""
#  Provider = "IPTV-EPG"
#  Username = "M3U-Identifier"  # From http://iptv-epg.com/[M3U-Identifier].m3u
#  Password = "XML-Identifier"  # From http://iptv-epg.com/[XML-Identifier].xml
  # THE FOLLOWING KEYS ARE OPTIONAL HERE; IF YOU"RE USING IPTV-EPG YOU'FE PROBABLY DONE YOUR
  # FILTERING THERE ALREADY
  # Filter = ""
  # FilterKey = ""
  # FilterRaw = false
  # Sort = ""

[[Source]]
  Provider = "Custom"
  M3U = "http://REAL WORKING M3U:8080/get.php?username=XXXpassword=YYYtype=m3u_plus\u0026output=ts"  # These can be either URLs or fully-qualified paths.
  EPG = "http://REAL WORKING EPG/epg/epg.xml.gz"
  # THE FOLLOWING KEYS ARE OPTIONAL IN THEORY, REQUIRED IN PRACTICE
  Filter = "*"
  FilterKey = "group-title" # FilterKey normally defaults to whatever the provider file says is best,
                            # otherwise you must set this.
  FilterRaw = false         # FilterRaw will run your regex on the entire line instead of just specific keys.
  Sort = "group-title"      # Sort will alphabetically sort your channels by the M3U key provided
# END TELLY CONFIG  ###############################################################################
```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```
/Users/USERNAME/.telly/telly -c /Users/USERNAME/.telly/telly.config.toml
```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```
```

**telly or docker log:**
```
INFO[2018-09-08T11:27:09+02:00] telly is preparing to go live (version=1.5.0, branch=HEAD, revision=811ea6be581f9bc8f2956d7c3892f2754b948e4d)
DEBU[2018-09-08T11:27:09+02:00] Build context (go=go1.10.3, user=root@8534dbdccf84, date=20180907-03:23:00)
DEBU[2018-09-08T11:27:09+02:00] Loaded configuration {
    "config": {
        "file": "/Users/USERNAME/.telly/telly.config.toml"
    },
    "database": {
        "file": "./telly.db"
    },
    "discovery": {
        "device-auth": "telly123",
        "device-firmware-name": "hdhomeruntc_atsc",
        "device-firmware-version": "20150826",
        "device-friendly-name": "telly",
        "device-id": 12345678,
        "device-manufacturer": "Silicondust",
        "device-model-number": "HDTC-2US",
        "device-uuid": "",
        "ssdp": true
    },
    "iptv": {
        "starting-channel": 10000,
        "streams": 1,
        "xmltv-channels": true
    },
    "log": {
        "level": "debug",
        "requests": true
    },
    "source": [
        {
            "EPG": "http://REAL WORKING EPG/epg/epg.xml.gz",
            "M3U": "http://REAL WORKING M3U:8080/get.php?username=XXXpassword=YYYtype=m3u_plus\u0026output=ts",
            "Provider": "Custom"
        }
    ],
    "version": false,
    "web": {
        "base-address": "192.168.1.35:6077",
        "listen-address": "0.0.0.0:6077"
    }
}
DEBU[2018-09-08T11:27:09+02:00] Checking migrations status and running any required migrations...
DEBU[2018-09-08T11:27:09+02:00] successfully applied 0 migrations to database
DEBU[2018-09-08T11:27:09+02:00] Context: Context build complete
DEBU[2018-09-08T11:27:09+02:00] creating webserver routes
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /metrics                  --> github.com/tellytv/telly/vendor/github.com/zsais/go-gin-prometheus.prometheusHandler.func1 (5 handlers)
[GIN-debug] GET    /epg.xml                  --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/guide/scan           --> github.com/tellytv/telly/internal/api.scanXMLTV (6 handlers)
[GIN-debug] GET    /api/lineups              --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] POST   /api/lineups              --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/lineups/:lineupId    --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] PUT    /api/lineups/:lineupId/channels --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] POST   /api/lineups/:lineupId/channels --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] PUT    /api/lineups/:lineupId/refresh --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/lineup/scan          --> github.com/tellytv/telly/internal/api.scanM3U (6 handlers)
[GIN-debug] GET    /api/guide_sources        --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] POST   /api/guide_sources        --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/guide_sources/channels --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/guide_sources/programmes --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/guide_source/:guideSourceId/coverage --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/guide_source/:guideSourceId/match --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/guide_source/:guideSourceId/lineups --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] PUT    /api/guide_source/:guideSourceId/lineups/:lineupId --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] DELETE /api/guide_source/:guideSourceId/lineups/:lineupId --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/guide_source/:guideSourceId/lineups/:lineupId/channels --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/video_sources        --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] POST   /api/video_sources        --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/video_sources/tracks --> github.com/tellytv/telly/internal/api.wrapContext.func1 (6 handlers)
[GIN-debug] GET    /api/streams              --> github.com/tellytv/telly/internal/api.ServeAPI.func1 (6 handlers)
INFO[2018-09-08T11:27:09+02:00] telly is live and on the air!
INFO[2018-09-08T11:27:09+02:00] Broadcasting from http://0.0.0.0:6077/
INFO[2018-09-08T11:27:09+02:00] EPG URL: http://0.0.0.0:6077/epg.xml
[GIN-debug] Listening and serving HTTP on 0.0.0.0:6077
**Additional information:**
```
